# AWS playbook
---

- name: Create spot instace request
  hosts: localhost
  connection: local
  
   
  tasks:
    - name: Get instance info
      amazon.aws.ec2_instance_info:
        aws_access_key: "{{ec2_access_key}}"
        aws_secret_key: "{{ec2_secret_key}}"
        region: us-east-1
        filters:
          instance-state-name: ["running"]
      register: ec2_node_info
    - debug:
        msg: "{{ ec2_node_info.instances[0].public_ip_address }}"

    - name: Add new instance to host group
      add_host:
         hostname: "{{ ec2_node_info.instances[0].public_ip_address }}"
         groupname: microk8s
         ansible_ssh_private_key_file: "/var/jenkins_home/ansible/kuber.pem"
      register: add_host
    - debug:
        msg: "{{ add_host }}"

- hosts: microk8s
  remote_user: ubuntu
  become: yes
  gather_facts: no
  roles:
    - role: racqspace.microk8s
      vars:
        microk8s_plugins:
          istio: true
          ingress: true
          dns: true
          helm3: true
          dashboard: true