# AWS playbook
---

- name: Create spot instace request
  hosts: localhost
  connection: local
  
   
  tasks:
    - name: Get instance info
      amazon.aws.ec2_instance_info:
        aws_access_key: "{{ec2_access_key}}"
        aws_secret_key: "{{ec2_secret_key}}"
        region: us-east-1
        filters:
          instance-state-name: ["running"]
      register: ec2_node_info
    - debug:
        msg: "{{ ec2_node_info.instances[0].public_ip_address }}"

    - name: Add new instance to host group
      add_host:
         hostname: "{{ ec2_node_info.instances[0].public_ip_address }}"
         groupname: microk8s
         ansible_ssh_private_key_file: "/var/jenkins_home/ansible/kuber.pem"
      register: add_host
    - debug:
        msg: "{{ add_host }}"

    - name: Wait 300 seconds for port 22 to become open and contain "OpenSSH"
      wait_for:
        port: 22
        host: '{{ ec2_node_info.instances[0].public_ip_address }}'
        delay: 10
      vars:
        ansible_connection: local
      register: check_port_result
    - debug:
        msg: "{{ check_port_result }}"

    
- hosts: microk8s
  remote_user: ubuntu
  become: yes
  gather_facts: no
  pre_tasks:
    - name: install python
      raw: 'sudo apt-get -y install python3'
  tasks:
    - name: update and upgrade
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Install Apache
      apt: 
        name: apache2
        state: present